apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: rabbitmq3
  name: rabbitmq3
spec:
  type: LoadBalancer
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: discovery
      port: 15672
      targetPort: 15672
  selector:
    io.kompose.service: rabbitmq3
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: rabbitmq3
  name: rabbitmq3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq3
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: rabbitmq3
    spec:
      containers:
        - env:
            - name: default_user
              value: guest
            - name: default_pass
              value: guest
          image: rabbitmq:management-alpine
          name: rabbitmq
          ports:
            - containerPort: 15672
              name: discovery
            - containerPort: 5672
              name: amqp
          resources: { }
      restartPolicy: Always