apiVersion: v1
kind: Service
metadata:
  name: newsservice
spec:
  type: LoadBalancer
  selector:
    app: youcan_backend
    tier: newsservice
  ports:
    - name: "3000"
      port: 80
      protocol: TCP
      targetPort: 3000
    - name : "https"
      port: 443
      protocol: TCP
      targetPort: 3000